apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  filebeat.yml: |
    # filebeat.inputs:
    #   - type: container
    #     paths:
    #       - /var/log/containers/*.log
    #     processors:
    #       - add_kubernetes_metadata:
    #           host: ${NODE_NAME}
    #           matchers:
    #           - logs_path:
    #               logs_path: "/var/log/containers/"

    filebeat.autodiscover:
      providers:
      - type: kubernetes
        templates:
        - condition:
            equals:
              kubernetes.namespace: {{ .Values.namespaceToWatch }}
          config:
          - type: container
            paths:
            - /var/log/containers/*-${data.kubernetes.container.id}.log
            exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines

    # filebeat.autodiscover:
    #  providers:
    #    - type: kubernetes
    #      node: ${NODE_NAME}
    #      hints.enabled: true
    #      hints.default_config:
    #        type: container
    #        paths:
    #          - /var/log/containers/*${data.kubernetes.container.id}.log

    # processors:
    #   - add_cloud_metadata:
    #   - add_host_metadata:

    output.logstash:
      hosts: ["{{ .Values.logstashName }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.logstashPort }}"]
